### ISSUE TITLE
SCF convergence difficulty

### ISSUE THREAD

**Issue by Migie-cphy** [hellozhaoming/FCP-vasp-ase#8]
When I was calculating the adsorption of H2O on my own catalyst substrate, after several ion steps, the fmax increased. Upon checking the VASP calculation, I found that SCF would not converge even after running 500 steps.
I also encountered this situation when calculating an H2O.

**Comment by hellozhaoming** [comment]
It might be a vasp converge issue. Please check your structure and NELECT.
